[project]
name = "api-session"
version = "1.7.0"
description = "requests.Session to work with JSON APIs"
authors = [{ name = "Baptiste Fontaine", email = "baptiste@bixoto.com" }]
requires-python = ">=3.10"
readme = "README.md"
license = "MIT"
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Development Status :: 5 - Production/Stable",
    "Programming Language :: Python :: 3",
]
dependencies = ["requests>=2.33,<3"]

[project.urls]
Homepage = "https://github.com/Bixoto/api-session"

[dependency-groups]
dev = [
    "mypy>=2,<3",
    "types-requests",
    "pytest>=8,<9",
    "pytest-cov>=7,<8",
    "ruff>=0,<1",
    "types-urllib3",
]

[tool.hatch.build.targets.sdist.force-include]
"api_session/py.typed" = "api_session/py.typed"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.coverage.report]
omit = ["tests/*"]
exclude_lines = [
    "pragma: nocover",
    "raise NotImplementedError",
    "except ImportError:",
]

[tool.ruff]
line-length = 120
target-version = "py310"
[tool.ruff.lint]
select = [
    "D", # docstrings
    "PERF", # Performance
    "W",
    "F",
    "UP", # deprecated Python
    # Flake8
    "A",
    "ASYNC",
    "B",
    "C4",
    "PIE800",
    "PT",
    "SIM",
    "SLOT",
    "YTT",

    "PLE",
    "FURB",
    "PLC0207",
]
ignore = [
    "D100", # "Missing docstring in public module"
    "D104", # "Missing docstring in public package"
    "D105", # "Missing docstring in magic method"
    "D107", # "Missing docstring in `__init__`"
    "D204", # "1 blank line required after class docstring"
    "D205", # "1 blank line required between summary line and description",
    "D208", # "Docstring is over-indented" (examples)
    "D400", # "First line should end with a period" (false-positives)
    "D401", # "First line of docstring should be in imperative mood"
    "D412", # "No blank lines allowed between a section header and its content"
    "D413", # "Missing blank line after last section"
    "D415", # "First line should end with a period, question mark, or exclamation point" (false-positives)

    "E402", # "Module level import not at top of file"
    "E501", # line too long
    "F401", # "unused" imports
]

[tool.ruff.lint.per-file-ignores]
"tests/*.py" = ["D"]
"conftest.py" = ["D"]
